### ISSUE TITLE
Upload to Drive Functionality

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [boypt/simple-torrent#11]
Please add upload to Cloud Storage.

Here it is already implemented https://github.com/Mrigank11/embetacloud or https://github.com/ParveenBhadooOfficial/BhadooCloud

**Comment by boypt** [comment]
upload to anywhere can be easily implimented by a simple script as `DoneCmd` option.

eg, with [gdrive](https://github.com/gdrive-org/gdrive) tool, a script of several lines is enough:

```bash
#!/bin/bash
UP="${CLD_DIR}/${CLD_PATH}"
gdrive upload "${UP}"
```

**Comment by ParveenBhadooOfficial** [comment]
People like me do not understand how to do it exactly without a working tutorial. :(

**Comment by nk932714** [comment]
love embeta cloud but it is based on npm so it is slower then cloud torrent. Both embeta cloud  & torrent cloud have their cons and pros.

**Comment by kazuma777** [comment]
> upload to anywhere can be easily implimented by a simple script as `DoneCmd` option.
> 
> eg, with [gdrive](https://github.com/gdrive-org/gdrive) tool, a script of several lines is enough:
> 
> ```shell
> #!/bin/bash
> UP="${CLD_DIR}/${CLD_PATH}"
> gdrive upload "${UP}"
> ```

Hi. if i do like this is going work?

` "DoneCmd": "/home/user/cmd.sh",`

in file .sh

`#!/bin/bash`
`UP="${CLD_DIR}/${CLD_PATH}"`
`gdrive sync upload "${UP}" <id_folder>`

**Comment by boypt** [comment]
> > upload to anywhere can be easily implimented by a simple script as `DoneCmd` option.
> > eg, with [gdrive](https://github.com/gdrive-org/gdrive) tool, a script of several lines is enough:
> > ```shell
> > #!/bin/bash
> > UP="${CLD_DIR}/${CLD_PATH}"
> > gdrive upload "${UP}"
> > ```
> 
> Hi. if i do like this is going work?
> 
> ` "DoneCmd": "/home/user/cmd.sh",`
> 
> in file .sh
> 
> `#!/bin/bash`
> `UP="${CLD_DIR}/${CLD_PATH}"`
> `gdrive sync upload "${UP}" <id_folder>`

almost there.
see the example script under [scripts/doneCMD.sh](https://github.com/boypt/simple-torrent/blob/master/scripts/doneCMD.sh)

you only need to run upload on `CLD_TYPE`=="file"`
