### ISSUE TITLE
ReverseProxy with Unix Socket

### ISSUE THREAD

**Issue by 2ral** [boypt/simple-torrent#110]
It can be more resource efficient to start a unix:scoket in case of hiding cloud-torrent behind nginx web server. I have not found such an option in documentation. I guess it should be technically possible to implement functionality of starting unix:socket

**Comment by boypt** [comment]
since ver 1.3.0

use `--host=unix://run/cld.sock`, or the env variable `HOST=unix://run/cld.sock` to listen on unix socket
