### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by Forden** [boypt/simple-torrent#116]
Do you have any plans on supporting ARM cpus in Docker? It would be cool to setup torrent box on Raspberry pi.

**Comment by dzmono** [comment]
> Do you have any plans on supporting ARM cpus in Docker? It would be cool to setup torrent box on Raspberry pi.

https://hub.docker.com/r/riftta/cloud-torrent

**Comment by boypt** [comment]
already supported in the latest version
