### ISSUE TITLE
Debian 10 Compatibility

### ISSUE THREAD

**Issue by 2ral** [boypt/simple-torrent#118]
Latest releases are not compatible with Debian 10, which is current stable branch of Debian OS

./cloud-torrent: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./cloud-torrent)

Last supported version is 1.2.15

**Comment by BenjaminLN** [comment]
me too

**Comment by boypt** [comment]
try version 1.2.22 binary with suffix "static"

**Comment by 2ral** [comment]
> try version 1.2.22 binary with suffix "static"

seems like the 1.2.22 static is crashing whenever torrent magnet link is redirected to simple-torrent instance. Rolling back to 1.2.15

**Comment by hkthomas** [comment]
I'm having this problem too, thank you very much for providing the "static" version, I'm now running stably on version 1.2.22

**Comment by hkthomas** [comment]
I added the directive "DisableUTP: true" to the configuration file, but the CPU usage was still high.
