### ISSUE TITLE
Crash on adding magnet via protocol handler

### ISSUE THREAD

**Issue by snowie2000** [boypt/simple-torrent#119]
https://github.com/boypt/simple-torrent/blob/1a095caf68e1afd46c7b2f25c233eaae6acfffc2/server/server_api.go#L40

is faulty. It should be 
```
c, err := ctstatic.ReadAll("files/template/magadded.html")
```

**Comment by 2ral** [comment]
I had stated that I had been suffering from the same problem in the comments of issue #118

**Comment by boypt** [comment]
fixed in latest release. thanks.
