### ISSUE TITLE
Error Loading Shared Library

### ISSUE THREAD

**Issue by capriciousduck** [boypt/simple-torrent#127]
Here's the error I'm getting while deploying the docker image.

Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/bin/cloud-torrent)
Jul 9 01:02:37 PM  Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/bin/cloud-torrent)
Jul 9 01:02:37 PM  Error relocating /usr/local/bin/cloud-torrent: _Znwm: symbol not found
Jul 9 01:02:37 PM  Error relocating /usr/local/bin/cloud-torrent: _ZdlPvm: symbol not found
Jul 9 01:02:37 PM  Error relocating /usr/local/bin/cloud-torrent: _Unwind_Resume: symbol not found
Jul 9 01:02:37 PM  Error relocating /usr/local/bin/cloud-torrent: __gxx_personality_v0: symbol not found

**Comment by boypt** [comment]
should be fixed in 5fc2a0bafbad3dfc7e58b95f325d371a18ac46d4
