### ISSUE TITLE
how to specify --config path for docker run?

### ISSUE THREAD

**Issue by vihatsoft** [boypt/simple-torrent#131]
when i run docker command in ubuntu not find cloud-torrent.json. where save config file while using docker?
and how to set config path for bellow docker command?

`$ docker run -d -p 3000:3000 -v /path/to/my/downloads:/downloads -v /path/to/my/torrents:/torrents boypt/cloud-torrent
`
thank you,

**Comment by boypt** [comment]
Just map the config file as a volume:

```
docker run --rm -p 3000:3000 \
	-v /tmp/downloads:/downloads \
	-v /tmp/torrents:/torrents \
	-v /tmp/cloud-torrent.yaml:/etc/cloud-torrent.yaml \
	boypt/cloud-torrent --debug
```

you can download an example config file from 
https://raw.githubusercontent.com/boypt/simple-torrent/master/example-cloud-torrent.yaml

But careful with the downloaddir and watchdir in the configure file, must match the mapping volume with the command you run.

Personally I prefer to use  `docker-compose`, see https://github.com/boypt/simple-torrent/blob/master/docker-compose.yml

Later I will draft some examples using docker

**Comment by vihatsoft** [comment]
thank you for your help.

**Comment by vihatsoft** [comment]
please post docker-compose example.

**Comment by boypt** [comment]
docker-compose.yaml is in the repo already

VihatSoft ***@***.***> 于 2021年7月27日周二 01:11写道：

**Comment by vihatsoft** [comment]
yes brother, got it. thank you
