### ISSUE TITLE
RSS error

### ISSUE THREAD

**Issue by anhthoai** [boypt/simple-torrent#132]
Hello, I have put RSS url but when I click to download, error happen as below, any help?
400 - Bad Request :POST:/api/magnet:ERROR: Magnet error: unexpected scheme "https"

**Comment by boypt** [comment]
The integrated RSS only works for those feeds provides a magnet link.
Actually I don't see many sites providing such feeds, eztv and dmhy is all I know of.

Normal RSS feeds only include link to the page, that's what this error means.

**Comment by anhthoai** [comment]
I'm using this https://nyaa.si/?page=rss&q=%5BHorribleSubs%5D&c=0_0&f=0

**Comment by boypt** [comment]
ok they did provide hash info in the feed.
I will add support in the next version
