### ISSUE TITLE
i can't access the page when using nginx for reverse proxy

### ISSUE THREAD

**Issue by lululus** [boypt/simple-torrent#133]
i reverse proxyed this app with a domain using nginx. i used the latest configuration in the wiki, but neither dedicated domain or shared domain would work.

everything seems to work just fine if i access the app with http://ip:port, but when i try to access it with my domain name, my browser just goes empty after i entered the password, nothing pops out, (however, the web titile does get changed, and there is something in the "Element" in F12)

i can't solve the problem, can you give me some advice?

**Comment by boypt** [comment]
paste your nginx config and screen capture on F12 "Network" could be helpful

**Comment by lululus** [comment]
![image](https://user-images.githubusercontent.com/30972308/128279447-3ff2a4c9-a78b-42b4-b381-973c0145f1b7.png)
![image](https://user-images.githubusercontent.com/30972308/128279771-5bd7976d-f9c9-41d9-8889-10dead92e122.png)
![image](https://user-images.githubusercontent.com/30972308/128279832-40173261-91c4-4b1b-bacf-0342da89b331.png)
![image](https://user-images.githubusercontent.com/30972308/128279857-7de7158a-04aa-42ef-b9d0-16955252cd1d.png)
![image](https://user-images.githubusercontent.com/30972308/128280076-add44a6f-0f67-4881-94a9-8526e3706bc3.png)

i barely modified the nginx config except for the listening port

**Comment by lululus** [comment]
ohhhhhhhh, i got it!
this app must be run with ssl certificate
now i now open it with my domain

**Comment by boypt** [comment]
yes, `proxy_pass http://...` means nginx only communicate upstream with the http protocol, not https.
