### ISSUE TITLE
Update docker latest tag to current version

### ISSUE THREAD

**Issue by rhurling** [boypt/simple-torrent#14]
Thank you very much for this client. It works great! 
The one thing I noticed is that the docker run command doesn't load the newest version of the client.

That seems to be because the `latest` [docker tag](https://hub.docker.com/r/boypt/cloud-torrent/tags) is set for a version that is a month old (1.0.7 as far as I can tell). Manually specifying the version worked, but just wanted to point the out of date latest tag out.

Not sure how you create new docker tag releases now, but you should be able to retag the latest to the newest version with the same command.

**Comment by boypt** [comment]
Oh somehow I left the autobuild switch off and forgot, it's now building, it should be ready in minutes.

**Comment by rhurling** [comment]
Okay, thanks!
