### ISSUE TITLE
Scalingo Error

### ISSUE THREAD

**Issue by capriciousduck** [boypt/simple-torrent#150]
Deploying this app on Scalingo got this error:

`Fetching source code
-----> Fetching jq... done
-----> Fetching stdlib.sh.v8... done
-----> 
       Detected go modules via go.mod
-----> 
       Detected Module Name: github.com/boypt/simple-torrent
-----> 
 !!    The go.mod file for this project does not specify a Go version
 !!    
 !!    Defaulting to go1.12.17
 !!    
 !!    For more details see: https://doc.scalingo.com/languages/go/gomod#configuration
 !!    
-----> New Go Version, clearing old cache
-----> Installing go1.12.17
-----> Fetching go1.12.17.linux-amd64.tar.gz... done
-----> Determining packages to install
       
       Detected the following main packages to install:
       		github.com/boypt/simple-torrent
       
-----> Running: go install -v -tags heroku github.com/boypt/simple-torrent 
build github.com/boypt/simple-torrent: cannot load crypto/ed25519: cannot find module providing package crypto/ed25519
 !     An error occurred during buildpack compilation
 !   Error deploying the application
 !   → Invalid return code from buildpack `

**Comment by capriciousduck** [comment]
What do I do now?

**Comment by boypt** [comment]
I'm not familiar with Scalingo, but the project needs at least go1.16 to compile .

Your log shows you are using go 1.12

**Comment by capriciousduck** [comment]
Ok. Thanks. I will look into it.
