### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [boypt/simple-torrent#166]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by boypt** [comment]
sadlly no.
I found that the go torrent lib is too CPU costcy at many scenerios, I myself switched to use qbitorrent (nox) instead. They're C++ based and have a more friendly torrent ecology.

**Comment by ghost** [comment]
Hi boypt.

> sadlly no.
> I found that the go torrent lib is too CPU costcy at many scenerios, I myself switched to use qbitorrent (nox) instead. They're C++ based and have a more friendly torrent ecology.

thank you for feedback.
