### ISSUE TITLE
add a support for private tracker & ability to resume when downloading via IDM

### ISSUE THREAD

**Issue by rvpn** [boypt/simple-torrent#17]
may i know wether this simple torrent only support for public tracker?

i can download from private tracker but i cannot seed them .

turning on "enable seeding" and set ratio to 1 also didnt work.

====================
 if i download multiple files via Internet Download Manager, i cannot resume the download session from where it left if something bad happened like my connection went down suddenly.

**Comment by boypt** [comment]
private/public trackers have no differences to torrent client.

normally a private torrent includes the private tracker address, no need to
add the tracker.

But this reminded me that the current mechanism adding public trackers to
all torrent is inappropriate, I will change it soon.

the download server module is not part of the project, personally I map the
download directory in the front web server to serve the static files. I
will look into it.

rvpn <notifications@github.com> 于 2019年9月14日周六 15:34写道：

**Comment by boypt** [comment]
downloading multiple files is an on-the-fly zipping processing, which means no zipped files is generated, all the files are compressed in memory as data stream, thus there's no way to known in advance the full size of the zipped file, thus, resuming is not working is this mode, work as intended.
