### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by kaz050457** [boypt/simple-torrent#19]
add proxy features

**Comment by boypt** [comment]
torrent is a internal mechanism of [anacrolix/torrent](https://github.com/anacrolix/torrent) , nothing i can do since the upstream havn't supported proxing

**Comment by anjeshshrestha** [comment]
proxy support has been added last year, https://github.com/anacrolix/torrent/issues/160
https://godoc.org/github.com/anacrolix/torrent#Config
