### ISSUE TITLE
Rebrand?

### ISSUE THREAD

**Issue by msberends** [boypt/simple-torrent#2]
Great project! I’d use a different software name based on the original software, if I were you. This is probably the best fork around, but I had to look down the (incredibly large) network tree of the original repository to find it. If you rebrand it, search engines and those ‘alternatives to’ websites will index it as separate software. Just like OpenOffice/LibreOffice and ownCloud/Nextcloud. 

Thanks for maintaining it so very, very well. Keep up the good work!

**Comment by MiguelAlcaino** [comment]
It happened exactly the same to me. And the DoneCmd option is exactly what I was looking for. Great job!

**Comment by boypt** [comment]
Glade to hear that the project helps.
The idea of rebranding makes sense, I'll make it shortly,
