### ISSUE TITLE
How is use reverse proxy used in simple-torrent?

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [boypt/simple-torrent#20]
Cloud URL: https://server.bhadoocloud.ga

Installed via command: docker run -d -p 80:3000 -v /path/to/my/downloads:/downloads -v /path/to/my/torrents:/torrents boypt/cloud-torrent

I want to use it like https://proxy.parveenbhadoo.com (this is in PHP) or like https://server1.bhadoocloud.ga/proxy/https://www.google.com/ (NodeJS)

Is it possible to use simple-torrent to use as reverseproxy to browse, if not please suggest something that can be.

**Comment by boypt** [comment]
see wiki page https://github.com/boypt/simple-torrent/wiki/ReverseProxy

**Comment by ParveenBhadooOfficial** [comment]
I read this, but i don't know where to enter this code.
