### ISSUE TITLE
[error looking up "router.silotis.us:6881"] and computer network congestion!

### ISSUE THREAD

**Issue by XIU2** [boypt/simple-torrent#23]
Error after adding BT: 
```
2019/10/04 23:34:58 error looking up "router.silotis.us:6881": lookup router.silotis.us: no such host
```
I didn't add this Trackers.

At the same time, my computer network has become very stuck, but the network card does not have a lot of traffic!

The download speed is fluctuating, either 0-30KB/s or 5MB/s+.

- When the file download speed is 0-30KB/s, the computer network is congested.
- When the file download speed is 5MB/s or more, the computer network returns to normal.

**PC: Windows 10 1903**

**Comment by boypt** [comment]
the address is a DHT bootstrap node, not a tracker, same was discussed upstream: https://github.com/anacrolix/dht/issues/18

and the node only resolved only AAAA record, if your DNS doesn't not support ipv6 such error could occur, just ignore it.

**Comment by boypt** [comment]
about the network situation, I think it's because of the connections excceed to some limitation.
While on windows I recommend use tradition torrent clients eg uTorrent, Bitcomet, they has more sophisticated control over connection on windows.
