### ISSUE TITLE
Can't install from Source

### ISSUE THREAD

**Issue by botjoin** [boypt/simple-torrent#24]
Hi. i want install from source using golang-go but i got error this.

`main.go:7:2: cannot find package "github.com/jpillora/opts" in any of:
        /usr/lib/go-1.10/src/github.com/jpillora/opts (from $GOROOT)
        /root/go/src/github.com/jpillora/opts (from $GOPATH)
gzip: cloud-torrent_linux_amd64: No such file or directory
`

**Comment by boypt** [comment]
the project needs go module since golang 1.11, it's better to use the
newest 1.13.1 to have it compiled.

botjoin <notifications@github.com> 于 2019年10月15日周二 19:37写道：

**Comment by botjoin** [comment]
Thank you very much!
