### ISSUE TITLE
How to remove authentication requirement

### ISSUE THREAD

**Issue by cinetube** [boypt/simple-torrent#25]
How to remove authentication so that the script doesn't require any user name or password?

**Comment by boypt** [comment]
You need to edit file `/etc/systemd/system/cloud-torrent.service` to remove the `-a 'user:ctorrent' ` part from the command line. then run the following cmd to have it taken effect.
```
systemctl daemon-reload
systemctl start cloud-torrent
```

I will add an interative question during the install script later.
