### ISSUE TITLE
Getting error while installing on raspberry pi

### ISSUE THREAD

**Issue by cinetube** [boypt/simple-torrent#28]
Getting error while installing on raspberry pi. Please check the attached image

![SNAG-0000](https://user-images.githubusercontent.com/23441775/68166610-0f14be00-ff8d-11e9-9861-6d6d6a62a02e.jpg)

**Comment by boypt** [comment]
obviously root permission is needed to run the oneline script, prepend
`sudo` to your command if you dont login as root.

**Comment by cinetube** [comment]
I tried as root. But still getting same result.

**Comment by boypt** [comment]
I cannot reproduce what you mentioned.
I have a raspberry-like board with an armv7l cpu, the script works as intended.
Maybe your board is with different CPU, try run the command in debug mode and paste the result here:

```
bash -x <(wget -qO- https://raw.githubusercontent.com/boypt/simple-torrent/master/scripts/quickinstall.sh)
```

difference is that `bash` with a `-x` arg

**Comment by cinetube** [comment]
Thanks. This `bash -x <(wget -qO- https://raw.githubusercontent.com/boypt/simple-torrent/master/scripts/quickinstall.sh)` worked.

**Comment by boypt** [comment]
OK, I guess this is a sideeffect of an other bug I fixed in the script. 
the `-x` args is not needed if everything's fine.
