### ISSUE TITLE
[Request] Deploy to heroku functionality

### ISSUE THREAD

**Issue by gloriagalla** [boypt/simple-torrent#3]
@boypt please add functionality to directly deploy this to heroku or may be deploy to heroku button (will be highly appreciated).

**Comment by vcptr** [comment]
Sorry I'm not familiar with heroku, if certain script/code is needed in the repo, a pull request is welcomed.

**Comment by boypt** [comment]
Sorry I'm not familiar with heroku , if certain code/scripts is needed in the repo, a pull request is welcomed.

**Comment by ParveenBhadooOfficial** [comment]
Heroku won't work as when Heroku Team finds about Torrents they will just block the script, already happened with Cloud Torrent.

**Comment by gloriagalla** [comment]
Is there any heroku like site to deploy this project remotely. Want to seed torrents on cloud then stream them directly.

**Comment by ParveenBhadooOfficial** [comment]
@gloriagalla use AWS
