### ISSUE TITLE
Deploy 2 on One Server

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [boypt/simple-torrent#31]
I deployed [BhadooCloud](https://github.com/ParveenBhadooOfficial/Bhadoo-Cloud) on bhadoocloud.ga at port 80:3000 . Now i also want to deploy simple-torrent on same server but at another port. What should i use in this.

`docker run -d -p 3000:3000 -v /path/to/my/downloads:/downloads -v /path/to/my/torrents:/torrents boypt/cloud-torrent`

**Comment by boypt** [comment]
just map to another port will do


-p 81:3000
