### ISSUE TITLE
Wrong Storage on AWS Cloud

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [boypt/simple-torrent#32]
https://bhadoocloud.ga shows wrong storage see below.

![1](https://user-images.githubusercontent.com/35890959/68647762-ac02c880-0544-11ea-95e2-5e384583804b.PNG)

![2](https://user-images.githubusercontent.com/35890959/68647769-af964f80-0544-11ea-83e6-112e3e3ce478.PNG)

**Comment by boypt** [comment]
Actually it's not wrong, the free space is calculated from total blocks of the disk, while filesystems defaultly reserve a 5% of space only to root user in case of a full disk paralysis the whole system.

you can check the reserved space by `sudo tune2fs -l /dev/sdX1`, and free up the space `sudo tune2fs -m 0 /dev/sdX1`

**Comment by boypt** [comment]
I found that there's also a problem in the calculation of free space in the js code.
Fixed in version 1.0.23, try it out.

**Comment by ParveenBhadooOfficial** [comment]
What about the index of files. Too much expanded index causes site to crash.
