### ISSUE TITLE
Remove torrent after DoneCmd

### ISSUE THREAD

**Issue by dswd** [boypt/simple-torrent#36]
It would be great if could add something in DoneCmd that tells SimpleTorrent to remove the torrent. This way, it would be safe to move the torrent data away from the downloads folder instead of creating a copy. Also this would allow for an automated cleanup in the DoneCmd script.

I got multiple ideas on how to implement this:
* Add a CLD_DELETE_MARKER variable pointing to a non-existing path that the DoneCmd can create (touch) to mark the torrent for deletion after executing DoneCmd
* Add a CLD_TORRENT_ID variable containing the internal ID of the torrent file so one can do REST calls in the DoneCmd script. This is the easiest way to implement it but it will break once you add protection for XSRF or Authentication. 
* Add a control socket (unix socket) where control commands can be sent. This solution is far more powerful than the previous solutions but requires more work.

I would add a pull request, but it is your project and I don't want to make the decision. Also I am not a go developer, so I could only implement option 1 and 2 on my own.

**Comment by boypt** [comment]
Good idea.

I like the second implementation, the existing API can be used.

The auth module needs to patch to allow localhost http calls without authentication. but like I myself use caddy to proxy, there seems be problems.  Maybe it's all right to pass the user:pass to the script too.  

This is just my first thoughts, I'll see into it soon.

**Comment by boypt** [comment]
I impliment it in version 1.0.24

an cmd argument `--rest-api` is added to listen to local trusted ports, and `DoneCmd` is provided with hash key and the rest_api variable. A simple call to curl can do what mentioned above.

an example script is provided [scripts/doneCMD.sh](/boypt/simple-torrent/blob/master/scripts/doneCMD.sh)

**Comment by dswd** [comment]
Thanks a lot!
