### ISSUE TITLE
Slow download

### ISSUE THREAD

**Issue by dausruddin** [boypt/simple-torrent#37]
I have tested many torrents especially Linux ISO, but the download can only peak at 1MB/s.
I have tried adding the same torrents on qBittorrent and Transmission and I got a lot faster speed. I got more than 20MB/s for Ubuntu ISO.

**Comment by boypt** [comment]
Have you configure the public trackers from [ngosang/trackerslist](https://github.com/ngosang/trackerslist) ?

In my instance downloading a Linux ISO could get a full speed of the interface.

I'll make the `TrackerListURL` option default to the trackerslist best list in next release.

**Comment by dausruddin** [comment]
My bad. I had "Download Rate" set to **High**. Solved it by setting to "Unlimited".

Anyway saving the configs for "Download Rate" doesn't reflect the change. I had to manually edit the setting file and restart the program.

**Comment by boypt** [comment]
OK.

I noticed the web config problem too, and worked with it in latest code, next release should be all working fine.
