### ISSUE TITLE
Put ads banner on html.

### ISSUE THREAD

**Issue by kazuma777** [boypt/simple-torrent#38]
Hi. i want use my ads banner on simple-torrent source. after `go build` is work fine in directory but if i move file `cloud-torrent` to `/usr/local/bin/` and command `cloud-torrent` my ads banner not showing

**Comment by vcptr** [comment]
See the script under static/generate.sh, it compress static files into a go module.

**Comment by boypt** [comment]
See the script under static/generate.sh , compress static files into a go module.

**Comment by kazuma777** [comment]
> See the script under static/generate.sh , compress static files into a go module.

Can you give example how to use script generate.sh?

i try got this

`fatal: not a git repository (or any of the parent directories): .git
static.go:1: running "go-bindata": exec: "go-bindata": executable file not found in $PATH
fatal: not a git repository (or any of the parent directories): .git`

**Comment by boypt** [comment]
Install go-bindata command:
`go get -v -u github.com/shuLhan/go-bindata/...`
Then run `go generate` under the static dir is enough.

The script is for git commited sources. The script under script/make_release.sh is the one I use.

**Comment by kazuma777** [comment]
> Install go-bindata command:
> `go get -v -u github.com/shuLhan/go-bindata/...`
> Then run `go generate` under the static dir is enough.
> 
> The script is for git commited sources. The script under script/make_release.sh is the one I use.

Thank you very much!

**Comment by kazuma777** [comment]
> Install go-bindata command:
> `go get -v -u github.com/shuLhan/go-bindata/...`
> Then run `go generate` under the static dir is enough.
> 
> The script is for git commited sources. The script under script/make_release.sh is the one I use.

if using version 1.1.0
i got error
`
fatal: not a git repository (or any of the parent directories): .git
~/simple-torrent-1.1.0/static ~/simple-torrent-1.1.0/static
fatal: not a git repository (or any of the parent directories): .git
Warning: static change and not commited
`

i need copy script from version 1.0.25
now is working.

**Comment by boypt** [comment]
yep, I changed the script on recent version.
The script is calling git command to get the git version from the source, if your source is downloaded instead of git clone , that would be the error message.

but what's actually works is not about git, is the go-bindata command, runinng `go generate` under `static` dir would do all the job.
