### ISSUE TITLE
magnet handler does not respect relative paths

### ISSUE THREAD

**Issue by supriyo-biswas** [boypt/simple-torrent#40]
First of all, thank you for maintaining this wonderful project :)

simple-torrent adds a magnet links handler which uses the URL `/api/magnet`. However, this breaks when you use a relative path, i.e. if I have it installed under `/torrent/api/magnet`, the handler that's installed breaks because it still sends you to `/api/magnet`.

Can you please look into this issue?

Thanks in advance.

**Comment by boypt** [comment]
should be fixed at ver 1.1.4, check it out
