### ISSUE TITLE
Remove CORS restriction

### ISSUE THREAD

**Issue by ketankr9** [boypt/simple-torrent#46]
Please allow cross site access. Especially to ```/api/``` calls, or else browser based applications like browser-extensions can't work.   

This can be achieved by editing ```server_http.go``` as demonstrated below. 

```
40.	//api call
41.	if strings.HasPrefix(r.URL.Path, "/api/") {
		w.Header().Set("Access-Control-Allow-Origin", "*")   // add this
		w.Header().Set("Access-Control-Allow-Headers", "authorization") //add this
```
This will also solve the issue that I am having of not being able to read response using a browser-extension from remote simple-torrent server. [https://github.com/ketankr9/cloud-torrent-extension/issues/1#issuecomment-570915569](https://github.com/ketankr9/cloud-torrent-extension/issues/1#issuecomment-570915569)

**Comment by boypt** [comment]
added in v1.2.1

**Comment by boypt** [comment]
@ketankr9 
Glad to see you have an extension project :)

simpletorrent has an undocumented API that can add magnet to the server too:
`http://...address:3000/api/magnet?m=maget:....`, it's use by the browser ProtocolHandler service.

other APIs are lately documented here:  https://github.com/boypt/simple-torrent/wiki/RestfulAPI

**Comment by ketankr9** [comment]
Now the browser-extension is able to read response from the simple-torrent server successfully, but **only when auth is disabled.**    

This is the security imposed by the browser, but the server side change can allow browsers to execute requests with Authorization header.

[https://github.com/ketankr9/cloud-torrent-extension/tree/auth](https://github.com/ketankr9/cloud-torrent-extension/tree/auth)
PS: I am not good with CORS.

**Comment by vcptr** [comment]
Simple Torrent added a pure REST API endpoint that do not follow the authorization, it's intended to  communicate with other programs. I think it suits your usage scenario.

See the  --rest-api argument

**Comment by boypt** [comment]
Simple Torrent added a pure REST API endpoint that do not follow the authorization, it's intended to communicate with other programs. I think it suits your usage scenario.

See the --rest-api argument
