### ISSUE TITLE
NginX reverse proxy

### ISSUE THREAD

**Issue by psycholyzern** [boypt/simple-torrent#5]
I'm just gonna paste this working reverse proxy configuration for nginx just in case someone needs it.

```
location /ctorrent/ {
    proxy_pass http://127.0.0.1:3000/;
}

location /sync {
    proxy_pass http://127.0.0.1:3000;
    proxy_set_header Connection '';
    proxy_http_version 1.1;
    chunked_transfer_encoding off;
    proxy_buffering off;
    proxy_cache off;
}
```
Replace `ctorrent` with any path you want. Credit to https://github.com/caddyserver/caddy/issues/677#issuecomment-196090013

**Comment by psycholyzern** [comment]
Anyway @boypt. In `js/velox.js`, path /sync has slash at the front 
```
var v = velox("/sync", $scope.state);
```
that prevents us to make path something like `/ctorrent/sync`. Can you fix it?

**Comment by boypt** [comment]
> Anyway @boypt. In `js/run.js`, path /sync has slash at the front
> 
> ```
> var v = velox("/sync", $scope.state);
> ```
> 
> that prevents us to make path something like `/ctorrent/sync`. Can you fix it?

I tried fixing it at f71901f  , seems working.

I use caddy on my own server, the equivalent config is like 
```
  proxy /ctorrent http://127.0.0.1:3000 {
    transparent
    without /ctorrent
  }
```

I will draft a document about reverse proxying later. Thanks.

**Comment by psycholyzern** [comment]
Thanks. It is working fine :)
This is my last configuration that is working 
```
location /ctorrent/ {
        proxy_pass http://127.0.0.1:3000/;
        location /ctorrent/sync {
            proxy_pass http://127.0.0.1:3000/sync;
            proxy_set_header Connection '';
            proxy_http_version 1.1;
            chunked_transfer_encoding off;
            proxy_buffering off;
            proxy_cache off;
        }
    }
```

**Comment by boypt** [comment]
@psycholyzern I thinks it's ok that all request goes to backend as HTTP1.1, thus `/sync` wont need to be in a seprate location.

Would you try:
```
location /ctorrent/ {
        proxy_pass http://127.0.0.1:3000/;
        proxy_http_version 1.1;
 }
```

I dont use nginx myself, I use caddy on the server, caddy talks to backend using HTTP1.1 defaultly so nothing special is needed.

If it's OK, I'll update the wikipage:  https://github.com/boypt/simple-torrent/wiki/ReverseProxy

**Comment by dausruddin** [comment]
Sorry, I forgot to respond here since I stopped using it.

I have installed again and unfortunately nginx configs in wiki doesn't work. Webpage would just stuck at "Connecting".

**Comment by vcptr** [comment]
Thanks, I update the wiki page according to your fix

**Comment by boypt** [comment]
Thanks, I update the wiki page according to your fix
