### ISSUE TITLE
Slow speed performance

### ISSUE THREAD

**Issue by 3xploiton3** [boypt/simple-torrent#52]
Slow performance speed,
Same file and trackerlist,

Multiple i try different torrent it seem slow

Example
Simple torrent around 4-7MB
Another bot average 8-20MB

![](https://i.imgur.com/buB1bBv.jpg)
Compare

Another leech bot
![](https://i.imgur.com/y8TdsBQ.jpg)

![](https://i.imgur.com/0HXNYFR.jpg)

**Comment by boypt** [comment]
If what you got is correct, 13.72 MBps equals 1.7MBytes per second, while simpletorrent got 5MBytes per second.

And what the bittorrent part does are in the core library, simpletorrent is merely a simple wraper shell, nothing i can do about it.

**Comment by 3xploiton3** [comment]
MBps mean MegaByte per second
Mbps mean Megabit per second
