### ISSUE TITLE
能加上连接节点信息吗？

### ISSUE THREAD

**Issue by daiaji** [boypt/simple-torrent#57]
比较简单易用的BT客户端（不提那种麻烦的客户端）比如FDM，他会显示哪些节点连上了你，显示速率，ip，客户端识别符，连接状态之类的，不显示节点的话，有时候都不知道是谁连接上了你，我都不知道我做种成功了没……
然后从网站搜索bt资源那个功能，发起https请求的话要用系统带的CA证书吗？还是直接用Go的？
另外就是本地化不做一下吗？

**Comment by boypt** [comment]
终端连接信息是在最后的showdebuginfo可以看到。

目前没有打算把功能做得太精细。也许你需要传统一点的bt客户端，比如qbitorrent。


daiaji <notifications@github.com> 于 2020年2月19日周三 11:46写道：

**Comment by daiaji** [comment]
支持[BEP-0005](https://en.wikipedia.org/wiki/Torrent_file#Distributed_hash_tables)用于实现纯P2P吗？

**Comment by boypt** [comment]
bt功能是第三方库提供的，这个项目只是个简单外壳，核心功能做不了的。

daiaji <notifications@github.com> 于 2020年2月19日周三 13:22写道：

**Comment by daiaji** [comment]
进标准的审查不知道还有几轮，库啥时候更新又是另外一码是了

**Comment by idcm** [comment]
> 进标准的审查不知道还有几轮，库啥时候更新又是另外一码事了

大神你是不是暂停后再点开始也不能继续下载

**Comment by daiaji** [comment]
@idcm 确实，停止后再开始就没速度了……
