### ISSUE TITLE
Multiple user with specific folder to download

### ISSUE THREAD

**Issue by mrlongshen** [boypt/simple-torrent#59]
Hi, first at all, thanks for this great script. Fyi, this is not a bugs. Just a general question.
is this simple torrent support multiple user ? 
If yes, how to add user A on port 3001 with home directory based on their username ?
What command should I run ? Thanks.

**Comment by boypt** [comment]
just run another instance with different folder/port will do.

**Comment by mrlongshen** [comment]
> just run another instance with different folder/port will do.

any example commands? tq
