### ISSUE TITLE
[Feature] Watch a directory for torrents

### ISSUE THREAD

**Issue by v-garcia** [boypt/simple-torrent#6]
Before all, thanks for giving a new start to this project,

A feature that i miss from rtorrent is the ability to watch a directory for new ``.torrent`` files and download them. 

Does it sound feasible ?

**Comment by boypt** [comment]
Good idea and the implementation is not complicated, I've added the feature in new release.
Try it out!

**Comment by v-garcia** [comment]
Wow that's fast ! I'll try and let you know

**Comment by v-garcia** [comment]
Working for me ! 
It's catching new torrents only while cloud-torrent is running, is that the intended behavior?

**Comment by boypt** [comment]
> Working for me !
> It's catching new torrents only while cloud-torrent is running, is that the intended behavior?

Do you mean the program should import all torrent file in the WatchDirectory on it's booting up? Sounds reasonable, I'll impliment it later.

**Comment by v-garcia** [comment]
Yes I think it's a better way to do it.
As you delete ``.torrent`` when you load them, it should be easy to implement.

**Comment by boypt** [comment]
> Yes I think it's a better way to do it.
> As you delete `.torrent` when you load them, it should be easy to implement.

Yes that what I have done, try version 1.0.7
https://github.com/boypt/simple-torrent/releases/latest

**Comment by v-garcia** [comment]
Yes very nice, everything is working perfectly on my side.
