### ISSUE TITLE
add letsencrypt TLS certificate support

### ISSUE THREAD

**Issue by marcograss** [boypt/simple-torrent#63]
simpletorrent can handle TLS https server on 443 for example or any other port

it would be nice to add letsencrypt certificate support.

there are several golang libraries that can automatically fetch a certificate and use it in basically 1 line of code.

for example with autocert or other user friendly crates https://godoc.org/golang.org/x/crypto/acme/autocert

that would be very useful for simple-torrent deployments since it can easily offer encryption both on the downloads and the Web UI.

**Comment by boypt** [comment]
I would recommend deploying simple-torrent behind caddy, let caddy handle the certificate stuffs.

During the application for letsencrypt cert, the program must be listening at port 80, normally 80 is occupated by web servers like nginx/apache, it'd be confusing and various for different users environment.
