### ISSUE TITLE
Nginx configuration not working anymore

### ISSUE THREAD

**Issue by rodonile** [boypt/simple-torrent#64]
The nginx configuration as explained in https://github.com/boypt/simple-torrent/wiki/ReverseProxy
doesn't seem to work anymore after upgrading to the latest version (I'm using the docker image). Has anyone also experienced the same issue and knows how to fix it? 
Here is my current configuration:

    location / {
        proxy_pass http://127.0.0.1:3000;
    }
    
    location /sync {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
    }

**Comment by misterbit-pro** [comment]
I have not the same issue du to its working, but the Website takes some time to load. Its writing disconected and after some time this message disappers. This also happend after a recent upgrade

**Comment by boypt** [comment]
![image](https://user-images.githubusercontent.com/1033514/78621886-3cf08c80-78b6-11ea-97f9-371005b5c528.png)

I don't see any problem here with my instance. Please provide more details, press F12 in your browser and find the `/sync` request.

**Comment by rodonile** [comment]
I get a 504 error on the first GET request to the website. Therefore the sync request is not attempted by the browser. Looks like nginx is not able to retrieve the application locally(?) However the application locally is working perfectly fine.

Here is what I get:
![simpletorrent](https://user-images.githubusercontent.com/57265953/78643226-36611580-78b4-11ea-9974-6f6e287cdbcd.jpg)

**Comment by boypt** [comment]
504 means nginx is unable to connect to your instance, connection timed-out.

Depending on how you deployed, just check the network, firewall iptables, etc..
