### ISSUE TITLE
Crash on certain torrent

### ISSUE THREAD

**Issue by snowie2000** [boypt/simple-torrent#65]
Add this link: magnet:?xt=urn:btih:30932B4ECCB2A09A180813509CD489752BA177AD
and it will crash immediately.

**Comment by boypt** [comment]
I believe it's an upstream bug failing to deal with this torrent's data. I'll report it to them.

**Comment by boypt** [comment]
follow up in this issue https://github.com/anacrolix/torrent/issues/387

**Comment by snowie2000** [comment]
Ok
