### ISSUE TITLE
System stats unavailable when running headless

### ISSUE THREAD

**Issue by cnelson** [boypt/simple-torrent#69]
When using this application via the [RestfulAPI](https://github.com/boypt/simple-torrent/wiki/RestfulAPI) without a web browser connected to the UI, System stats are unavailable from `/api/stat` due to [this check](https://github.com/boypt/simple-torrent/blob/master/server/server_bg.go#L44).

Would you accept a simple PR to remove that check so stats are available to API-only clients?

**Comment by boypt** [comment]
Now call to `/api/stat` updates stat data.

**Comment by cnelson** [comment]
Thanks for the quick fix!
