### ISSUE TITLE
[enhancement] Add an /healtz endpoint.

### ISSUE THREAD

**Issue by v-garcia** [boypt/simple-torrent#7]
A good thing for containerized apps is to have an endpoint for checking if the app is alive.
The   [convention](https://stackoverflow.com/questions/43380939/where-does-the-convention-of-using-healthz-for-application-health-checks-come-f) wants an endpoint ``/healtz`` witch returns a successful http code and an empty body.

More info [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request).

Note that this endpoint must be authentication free, even with ``--auth`` specified.

**Comment by boypt** [comment]
ok, that's a small change.

try with 1.0.8, it's now building on docker hub.

I guess you use a docker image? I think it's unnecessary to relase a binary verson for this small change.

**Comment by v-garcia** [comment]
Tested ! Good work ! Yes I'm using the docker no need to release binary.
