### ISSUE TITLE
Share cloud torrent link to my friend without see my peer download.

### ISSUE THREAD

**Issue by kazuma777** [boypt/simple-torrent#76]
i want share to my friend but my friend can see my peer download.
this so risk because if anyone can get link http://ip:3000 people can disturb my peer download. 
i know can do auth user & pass but only can do one auth.

So my request is if other people open my link cloud torrent other pc device or different ip address or something like cookies, cache, no one can't see my peer download.

screenshot example open incognito browser people can see if other pc device.
![Untitled (Recovered)](https://user-images.githubusercontent.com/24896519/82015176-b8610d00-96b0-11ea-8f4e-b9e6a58c99bc.png)

**Comment by boypt** [comment]
I suggest setting up a nginx or caddy server that browse the download folder, share the address to your friend and they can see the file as a simple list page.
