### ISSUE TITLE
Nginx reverse proxy config not working

### ISSUE THREAD

**Issue by m4tt72** [boypt/simple-torrent#78]
Nginx reverse proxy config is not working.
I'm running simple-torrent on docker, as well as the reverse proxy server.
Here's my config:
```
location / {
    proxy_pass http://127.0.0.1:3000;
}

location /sync {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
}
```
![image](https://user-images.githubusercontent.com/20604769/83870605-731b8280-a726-11ea-97bf-3cf2f744b84e.png)

**Comment by Dibbyo456** [comment]
Are you using pure nginx or nginx+apache?

**Comment by boypt** [comment]
maybe you need to enable nginx debug level logs to see what happened.
The same configure works in my node.

**Comment by m4tt72** [comment]
@Dibbyo456 
> Are you using pure nginx or nginx+apache?

I am using pure nginx.

## Fixed

I somehow fixed the issue by using the following config:

```
// nginx.conf
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

server {
  server_name servername;
  listen 443 ssl http2;

  location / {
          proxy_pass http://torrents:3000;
  }

    location /sync {
      proxy_pass http://torrents:3000;
      proxy_set_header Connection '';
      proxy_http_version 1.1;
      chunked_transfer_encoding off;
      proxy_buffering off;
      proxy_cache off;
    }
}
```

I also reinstalled nginx, so there might be an issue that I had with it and by reinstalling it was fixed?

**Comment by boypt** [comment]
simple-torrent does not use websocket connections, there's no Upgrade header in the request. I think it's unrelated, maybe a browser cache problem
