### ISSUE TITLE
Incorrect file size

### ISSUE THREAD

**Issue by rockydares** [boypt/simple-torrent#79]
After downloading a file from torrent, the size shows 1GB when the actual file size is 1.4 or 1.5GB

**Comment by VDuyHoang** [comment]
just recheck, how did you know it 's 1.4 or 1.5GB, is torrent finished ?

**Comment by rockydares** [comment]
![IMG_20200607_105208](https://user-images.githubusercontent.com/66517282/83961027-f9fa6780-a8ac-11ea-808a-cc8cb16e31f2.jpg)
Here's a screenshot of the problem.

**Comment by VDuyHoang** [comment]
It's just round number,

**Comment by rockydares** [comment]
Round number doesn't always help.

**Comment by daiaji** [comment]
有一说一，一斤半的肉不该被说成是两斤或者一斤吧
