### ISSUE TITLE
Add a protocol handler for magnet links

### ISSUE THREAD

**Issue by DooML** [boypt/simple-torrent#8]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler

**Comment by boypt** [comment]
implimented in a1142c9 , checkout v1.0.11

**Comment by DooML** [comment]
Wow that was quick, thank you.

**Comment by DooML** [comment]
After I tested the new build, I've noticed that it only runs on an HTTPS site, which basically is bad practice because most local servers aren't secure of course. Here's proof that it can run on non-secure sites too :
![image](https://user-images.githubusercontent.com/26717942/63042788-a86a9180-bec2-11e9-9a1d-2991b04b505a.png)

**Comment by boypt** [comment]
well, the document says the feature works only on https sites. but now it looks like not all browser works this way. I should leave it to the browser to decide whether to support or now.

**Comment by boypt** [comment]
v1.0.11 has been discarded and updated with v1.0.12
