### ISSUE TITLE
Not working with Argo Tunnel

### ISSUE THREAD

**Issue by dausruddin** [boypt/simple-torrent#83]
Hi. I wanted to test simple-torrent with Argo Tunnel, but it stuck at "Connecting" page
> ![image](https://user-images.githubusercontent.com/5763466/86532227-c84fdd00-befa-11ea-9a8b-120c471e3575.png)

There is an error in Dev Console tab
`Firefox can’t establish a connection to the server at https://worker-ind-ensures-parliament.trycloudflare.com/sync.`
> ![image](https://user-images.githubusercontent.com/5763466/86532244-f8977b80-befa-11ea-9cb5-05dd1dfcbffa.png)

And got this in Network tab
> ![image](https://user-images.githubusercontent.com/5763466/86532366-f41f9280-befb-11ea-984b-95ffe95dd3e1.png)

Just in case you want to try, look for it here: https://developers.cloudflare.com/argo-tunnel/trycloudflare

Thanks in advanced!

**Comment by enniosousa** [comment]
I ever had used argo tunel, but it maybe can help you https://github.com/boypt/simple-torrent/wiki/ReverseProxy#full-example-nginx-with-shared-domain-under-a-directory
