### ISSUE TITLE
Simple torrent help needed!

### ISSUE THREAD

**Issue by imranext** [boypt/simple-torrent#99]
Is there any way to disable editing config option on the web page of simple torrent?

Can you please send me a auto install script that has no config editing option on menu of web page?

Or let me know how to customize and install (html,css files) of simple torrent? 

Love from
Bangladesh ❤

**Comment by supriyo-biswas** [comment]
You can put a server like nginx or caddy in front of Cloud torrent, and then add a location block for the `api/configure` to return 403.

This way, even though the configuration options might be visible, you won't be able to actually change the configuration in question.
